version: "3.9"
services: 
  app:
    build: .
    networks:
      - app-net
    ports: 
      - 5000:5000
    depends_on: 
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: fol-tw
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: secret
    networks:
      - app-net

networks: 
  app-net: