version: "3.9"
services: 
  app:
    build: .
    networks:
      - app-net
    ports: 
      - 5000:5000
    depends_on: 
      - db
  db:
    image: redis:alpine
    networks:
      - app-net

networks: 
  app-net: